config/routes.rb
Rails.application.routes.draw do
  root 'homes#show', via: :get
  resource :dashboard, only: :show
  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create, :show]
  resources :photo_shouts, only: [:create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :index] do
    post 'follow', to: 'following_relationships#create'
    delete 'follow', to: 'following_relationships#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following_relationship.rb
class FollowingRelationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/photo_shout.rb
class PhotoShout < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true
  default_scope { order(created_at: :desc) }
  validates_associated :content
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :shouts


  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: 'FollowingRelationship'

  has_many :followed_users, through: :followed_user_relationships


  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: 'FollowingRelationship'

  has_many :followers, through: :follower_relationships

  def following? user
    followed_user_ids.include? user.id
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.shouts
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController

  def create
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    current_user.unfollow(user)
    redirect_to user
  end

  private
  def user
     @_user ||= User.find(params[:user_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check_logged_in_user

  def show
  end

  private
  def check_logged_in_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController

  def show
    
  end

  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "Error"
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def build_content
    PhotoShout.new(photo_shout_params)
  end

  def photo_shout_params
    params.require(:photo_shout).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

  def show
    @shout = Shout.find(params[:id])
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController

  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "Successfully created..."
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def build_content
    TextShout.new(text_shout_params)
  end

  def text_shout_params
    params.require(:text_shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
require 'digest/md5'

module ShoutsHelper
  def gravatar user, size = 48
    digest = Digest::MD5.hexdigest(user.email.downcase)
    image_tag("http://gravatar.com/avatar/#{digest}?s=#{size}")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button user
    if current_user.following? user
      button_to 'Unfollow', user_follow_path(user), method: :delete
    else
      button_to 'Follow', user_follow_path(user)
    end
  end
end

app/views/dashboards/show.html.erb
<h1>My Dashboard</h1>

<%= form_for @text_shout do |f| %>
  <%= f.text_field :body, placeholder: 'Enter shout content here...' %>
  <%= f.submit 'Shout' %>
<% end %>

<%= form_for @photo_shout do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

<%= render @shouts %>

app/views/homes/show.html.erb
<h1>Welcome to Shouter!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonbanShouter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div>
      <% if signed_in? %>
        <%= link_to current_user.username, root_path %>
        <%= link_to 'Sign Out', session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_session_path %>
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
    </div>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to (image_tag photo_shout.image.url(:thumb)), photo_shout.image.url %>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
  <%= gravatar shout.user %>
  <%= link_to shout.user.username, shout.user %> Shouted:
  <div>
    <%= render shout.content %>
  </div>
  <%= link_to (time_ago_in_words(shout.created_at) + ' ago'), shout %>
<% end %>

app/views/shouts/show.html.erb
<h1>Shout Page</h1>

<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div><%= link_to user.username, user %></div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, require: true, autofocus: true %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>&nbsp;show page</h1>
<%= follow_button @user %>

<%= render @user.shouts %>